name: Python Greetings CD

on:
  push:
    branches: [main]

jobs:
  install-pip-deps:
    name: Install dependencies
    runs-on: self-hosted
    steps:
      - uses: ./.github/actions/install-pip-deps

  deploy-to-dev:
    name: Deploy to Dev
    needs: install-pip-deps
    runs-on: self-hosted
    steps:
      - uses: ./.github/actions/deploy-app
        with:
          env_name: dev
          port: 7001

  tests-on-dev:
    name: Test on Dev
    needs: deploy-to-dev
    runs-on: self-hosted
    steps:
      - uses: ./.github/actions/test-app
        with:
          env_name: dev

  deploy-to-staging:
    name: Deploy to Staging
    needs: tests-on-dev
    runs-on: self-hosted
    steps:
      - uses: ./.github/actions/deploy-app
        with:
          env_name: staging
          port: 7002

  tests-on-staging:
    name: Test on Staging
    needs: deploy-to-staging
    runs-on: self-hosted
    steps:
      - uses: ./.github/actions/test-app
        with:
          env_name: staging

  deploy-to-preprod:
    name: Deploy to Preprod
    needs: tests-on-staging
    runs-on: self-hosted
    steps:
      - uses: ./.github/actions/deploy-app
        with:
          env_name: preprod
          port: 7003

  tests-on-preprod:
    name: Test on Preprod
    needs: deploy-to-preprod
    runs-on: self-hosted
    steps:
      - uses: ./.github/actions/test-app
        with:
          env_name: preprod

  deploy-to-prod:
    name: Deploy to Prod
    needs: tests-on-preprod
    runs-on: self-hosted
    steps:
      - uses: ./.github/actions/deploy-app
        with:
          env_name: prod
          port: 7004

  tests-on-prod:
    name: Test on Prod
    needs: deploy-to-prod
    runs-on: self-hosted
    steps:
      - uses: ./.github/actions/test-app
        with:
          env_name: prod
